steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx:6.0.3
    settings:
      repo: ["${CI_REPO_OWNER%%io}/${CI_REPO_NAME}"]
      tags: "${CI_COMMIT_TAG##v}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*
